spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: usuarios-service
          uri: lb://usuarios
          predicates:
            - Path=/usuarios/**
          filters:
            - StripPrefix=1
        - id: notas-service
          uri: lb://notas
          predicates:
            - Path=/notas/**
          filters:
            - StripPrefix=1
        - id: mensajeria-service
          uri: lb://mensajeria
          predicates:
            - Path=/mensajeria/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
