spring:
  application:
    name: notas # Cambiado para identificar este microservicio en Eureka
  datasource:
    url: jdbc:mysql://localhost:3306/libro_usuarios
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  
  codec:
    max-in-memory-size: 2MB 

server:
  port: 9002

eureka:
  client:
    enabled: false
    
logging:   
  level:
    root: INFO
    com.proyecto.notas: DEBUG 
    org.springframework.web.reactive.function.client.WebClient: DEBUG 
  file:
    name: logs/notas-service.log 
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html